spring:
  application:
    name: tempo-demo
  profiles:
    active: dev
    
server:
  port: 18001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defalutZone: http://localhost:${server.port}/eureka/
      
tempo:
  demo:
    test: auto-flash
